In [34]:
#Decision Tree Alogorithm
import numpy as np
import pandas as pd

dataset=pd.read_csv('car.csv',names=['buying','maint','doors','person','lug_boot','safety','class'])
print("First 5 records")
dataset.head()

First 5 records


buying  maint doors person lug_boot safety  class
0  vhigh  vhigh     2      2    small    low  unacc
1  vhigh  vhigh     2      2    small    med  unacc
2  vhigh  vhigh     2      2    small   high  unacc
3  vhigh  vhigh     2      2      med    low  unacc
4  vhigh  vhigh     2      2      med    med  unacc

In [3]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   person    1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [4]:
dataset.describe()

buying  maint doors person lug_boot safety  class
count    1728   1728  1728   1728     1728   1728   1728
unique      4      4     4      3        3      3      4
top     vhigh  vhigh     2      2    small    low  unacc
freq      432    432   432    576      576    576   1210

In [5]:
dataset['class'],class_names=pd.factorize(dataset['class'])
print(class_names)

Index(['unacc', 'acc', 'vgood', 'good'], dtype='object')


In [6]:
print(dataset['class'].unique())

[0 1 2 3]


In [9]:
dataset['buying'],_=pd.factorize(dataset['buying'])
dataset['maint'],_=pd.factorize(dataset['maint'])
dataset['doors'],_=pd.factorize(dataset['doors'])
dataset['person'],_=pd.factorize(dataset['person'])
dataset['lug_boot'],_=pd.factorize(dataset['lug_boot'])
dataset['safety'],_=pd.factorize(dataset['safety'])

dataset.head()

buying  maint  doors  person  lug_boot  safety  class
0       0      0      0       0         0       0      0
1       0      0      0       0         0       1      0
2       0      0      0       0         0       2      0
3       0      0      0       0         1       0      0
4       0      0      0       0         1       1      0

In [10]:
x=dataset.iloc[:,:-1].values
print(x)

[[0 0 0 0 0 0]
 [0 0 0 0 0 1]
 [0 0 0 0 0 2]
 ...
 [3 3 3 2 2 0]
 [3 3 3 2 2 1]
 [3 3 3 2 2 2]]


In [11]:
y=dataset.iloc[:,-1]
print(y)

0       0
1       0
2       0
3       0
4       0
       ..
1723    3
1724    2
1725    0
1726    3
1727    2
Name: class, Length: 1728, dtype: int64


In [14]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.30,random_state=0)
print(x_train)

[[1 1 1 1 1 1]
 [2 3 0 2 2 2]
 [3 3 1 2 0 0]
 ...
 [3 3 1 0 2 0]
 [1 1 0 2 0 1]
 [1 2 1 1 0 0]]


In [17]:
from sklearn.tree import DecisionTreeClassifier
dtree=DecisionTreeClassifier(criterion='entropy',max_depth=3,random_state=0)

dtree.fit(x_train,y_train)
y_pred=dtree.predict(x_test)
print(y_pred)

[1 0 0 0 0 1 0 1 1 1 0 0 1 0 0 1 0 0 0 1 1 1 1 0 0 0 0 0 0 0 1 0 0 0 1 0 0
 0 0 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 0 0 0 0 1 1 0 0 0 1 0 0 0 0 0 0 1 0 1
 1 1 0 1 0 0 0 0 1 1 0 0 0 1 0 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 1 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0
 1 0 1 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 1 0 0
 0 1 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1
 0 1 0 0 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 1 1 1 1 0 0
 0 1 0 0 1 0 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 0 1 0 0
 0 0 0 1 0 1 1 1 1 0 1 0 0 0 1 1 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1
 0 1 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 1 0 0 0 0 1 1 0 0 0 1
 0 0 0 1 0 0 0 1 0 1 1 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 1 0 1 0 0 1 0 0
 0 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 0 0
 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0
 0 0 1 1 0 0 0 0 0 0 0 0 

In [27]:
from sklearn.metrics import classification_report,confusion_matrix
print("Classification Report : \n",classification_report(y_test,y_pred))
print("\n Confusion Matrix : \n",confusion_matrix(y_test,y_pred))

Classification Report : 
               precision    recall  f1-score   support

           0       0.89      0.96      0.93       363
           1       0.57      0.63      0.60       115
           2       0.00      0.00      0.00        16
           3       0.00      0.00      0.00        25

    accuracy                           0.82       519
   macro avg       0.37      0.40      0.38       519
weighted avg       0.75      0.82      0.78       519


 Confusion Matrix : 
 [[350  13   0   0]
 [ 42  73   0   0]
 [  0  16   0   0]
 [  0  25   0   0]]


/home/sjcet/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sjcet/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/home/sjcet/anaconda3/lib/python3.9/site-packages/sklearn/metrics/_classification.py:1248: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [30]:
from sklearn.metrics import accuracy_score
print("Accuracy : \n",accuracy_score(y_test,y_pred))

Accuracy : 
 0.815028901734104


In [31]:
df=pd.DataFrame({'Real Values':y_test,'Predicted Values':y_pred})
df

Real Values  Predicted Values
1318            0                 1
124             0                 0
648             0                 0
249             0                 0
1599            0                 0
...           ...               ...
906             0                 0
309             0                 0
838             0                 0
1076            1                 1
1453            1                 1

[519 rows x 2 columns]

In [32]:
print("Mislabelled Classifications : ",(y_test!=y_pred).sum())

Mislabelled Classifications :  96
